### ISSUE TITLE
Unable to install on ubuntu

### ISSUE THREAD

**Issue by tallandtree** [JFrogDev/bower-art-resolver#17]
Due to issue in package: util.

See: https://github.com/defunctzombie/node-util/issues/13. 

I needed to change the package.json.

**Comment by eyalbe4** [comment]
@tallandtree, If understand you're saying, the issue on Ubuntu is caused due to these 2 dependencies declaration:
"util": "^0.10.3" and "process": "^0.11.1",
which are added by the jinder/path package. You're also saying that forcing a specific version for those dependencies solves the issue. If this is true, it would probably be better to fix this in the jinder/path package, We can also force those versions in the bower-art-resolver package.json. Please see that it indeed fixes the issue for you and if all is working fine, we'd gladly accept a pull request with this change.

**Comment by tallandtree** [comment]
@eyalbe4, after a mere 2 days of struggling with this, and also submitting an issue to the util development tracker, it now works ok with version util@0.10.3. Yesterday I could not install util@0.10.3 with said error, only util@0.10.0 could be installed without error. I don't know if anyone changed anything related to this, but I don't think npm is very reliable. I can't imagine it is due to my environment, as I have tried several different environments (also different networks, at home and at work): several installations in a clean docker image, installation on a virtualbox with ubuntu, explicitely cleaning npm cache, etc. All same erroneous result. But now I can run docker build on the same dockerfile and it runs ok. Weird. I will close this issue now, but it does feel like hocus pocus to me.

**Comment by eyalbe4** [comment]
Glad to hear you managed resolve the issue for now @tallandtree.
